Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -15,13 +15,6 @@ jobs:
 
       - name: second step
         run: echo "second step executed"
-      - name: fail if TODO exists
-        run: |
-          if grep -R "TODO" .; then
-            echo "Found TODO. Failing build."
-            exit 1
-          else
-            echo "No TODOs found."
         
   secondjob:
     runs-on: ubuntu-latest
@@ -31,6 +24,13 @@ jobs:
       - name: fetch the repo
         run: |
           ls -a
+      - name: fail if TODO exists
+        run: |
+          if grep -R "TODO" .; then
+            echo "Found TODO. Failing build."
+            exit 1
+          else
+            echo "No TODOs found."
           echo "repo downloaded"
       - name: second step of second job
         run: echo "end"
